-- Tabel modul keuangan (lihat dokumentasi bagian 9) beserta sumber biaya kunjungan yang ditagihkan otomatis:
-- tindakan medis, tindakan keperawatan, pemeriksaan laboratorium dan penjualan farmasi.
-- Tabel sumber biaya hanya memuat kolom yang dibaca modul keuangan; modul klinisnya dikelola aplikasi lain.

CREATE TABLE service_tariffs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    clinic_id BIGINT UNSIGNED NOT NULL,
    code VARCHAR(20) NOT NULL,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(30) NOT NULL,
    price DECIMAL(15,2) NOT NULL DEFAULT 0,
    description TEXT NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    UNIQUE KEY service_tariffs_clinic_id_code_unique (clinic_id, code),
    KEY service_tariffs_clinic_id_category_index (clinic_id, category),
    CONSTRAINT service_tariffs_clinic_id_foreign FOREIGN KEY (clinic_id) REFERENCES clinics (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE cash_sessions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    clinic_id BIGINT UNSIGNED NOT NULL,
    user_id BIGINT UNSIGNED NULL,
    number VARCHAR(30) NOT NULL,
    status VARCHAR(20) NOT NULL,
    opened_at TIMESTAMP NOT NULL,
    opening_balance DECIMAL(15,2) NOT NULL DEFAULT 0,
    opening_notes TEXT NULL,
    closed_at TIMESTAMP NULL,
    expected_cash DECIMAL(15,2) NULL,
    counted_cash DECIMAL(15,2) NULL,
    difference DECIMAL(15,2) NULL,
    closing_notes TEXT NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    UNIQUE KEY cash_sessions_clinic_id_number_unique (clinic_id, number),
    KEY cash_sessions_user_id_status_index (user_id, status),
    KEY cash_sessions_clinic_id_opened_at_index (clinic_id, opened_at),
    CONSTRAINT cash_sessions_clinic_id_foreign FOREIGN KEY (clinic_id) REFERENCES clinics (id) ON DELETE CASCADE,
    CONSTRAINT cash_sessions_user_id_foreign FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE medical_actions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    clinic_id BIGINT UNSIGNED NOT NULL,
    visit_id BIGINT UNSIGNED NOT NULL,
    service_tariff_id BIGINT UNSIGNED NULL,
    user_id BIGINT UNSIGNED NULL,
    performed_at TIMESTAMP NOT NULL,
    description VARCHAR(255) NOT NULL,
    quantity INT UNSIGNED NOT NULL,
    unit_price DECIMAL(15,2) NOT NULL DEFAULT 0,
    subtotal DECIMAL(15,2) NOT NULL DEFAULT 0,
    notes TEXT NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    KEY medical_actions_clinic_id_performed_at_index (clinic_id, performed_at),
    CONSTRAINT medical_actions_clinic_id_foreign FOREIGN KEY (clinic_id) REFERENCES clinics (id) ON DELETE CASCADE,
    CONSTRAINT medical_actions_visit_id_foreign FOREIGN KEY (visit_id) REFERENCES visits (id) ON DELETE CASCADE,
    CONSTRAINT medical_actions_service_tariff_id_foreign FOREIGN KEY (service_tariff_id) REFERENCES service_tariffs (id) ON DELETE SET NULL,
    CONSTRAINT medical_actions_user_id_foreign FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE nursing_actions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    clinic_id BIGINT UNSIGNED NOT NULL,
    visit_id BIGINT UNSIGNED NOT NULL,
    service_tariff_id BIGINT UNSIGNED NULL,
    user_id BIGINT UNSIGNED NULL,
    performed_at TIMESTAMP NOT NULL,
    description VARCHAR(255) NOT NULL,
    quantity INT UNSIGNED NOT NULL,
    unit_price DECIMAL(15,2) NOT NULL DEFAULT 0,
    subtotal DECIMAL(15,2) NOT NULL DEFAULT 0,
    notes TEXT NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    KEY nursing_actions_clinic_id_performed_at_index (clinic_id, performed_at),
    CONSTRAINT nursing_actions_clinic_id_foreign FOREIGN KEY (clinic_id) REFERENCES clinics (id) ON DELETE CASCADE,
    CONSTRAINT nursing_actions_visit_id_foreign FOREIGN KEY (visit_id) REFERENCES visits (id) ON DELETE CASCADE,
    CONSTRAINT nursing_actions_service_tariff_id_foreign FOREIGN KEY (service_tariff_id) REFERENCES service_tariffs (id) ON DELETE SET NULL,
    CONSTRAINT nursing_actions_user_id_foreign FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE lab_orders (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    clinic_id BIGINT UNSIGNED NOT NULL,
    visit_id BIGINT UNSIGNED NOT NULL,
    user_id BIGINT UNSIGNED NULL,
    number VARCHAR(20) NOT NULL,
    priority VARCHAR(10) NOT NULL DEFAULT 'routine',
    status VARCHAR(20) NOT NULL,
    requested_at TIMESTAMP NOT NULL,
    completed_at TIMESTAMP NULL,
    cancelled_at TIMESTAMP NULL,
    cancellation_reason VARCHAR(255) NULL,
    total_price DECIMAL(15,2) NOT NULL DEFAULT 0,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    CONSTRAINT lab_orders_clinic_id_foreign FOREIGN KEY (clinic_id) REFERENCES clinics (id) ON DELETE CASCADE,
    CONSTRAINT lab_orders_visit_id_foreign FOREIGN KEY (visit_id) REFERENCES visits (id) ON DELETE CASCADE,
    CONSTRAINT lab_orders_user_id_foreign FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE lab_order_items (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    lab_order_id BIGINT UNSIGNED NOT NULL,
    service_tariff_id BIGINT UNSIGNED NULL,
    test_name VARCHAR(255) NOT NULL,
    section VARCHAR(30) NOT NULL DEFAULT '',
    unit_price DECIMAL(15,2) NOT NULL DEFAULT 0,
    quantity SMALLINT UNSIGNED NOT NULL DEFAULT 1,
    total_price DECIMAL(15,2) NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL,
    notes TEXT NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    CONSTRAINT lab_order_items_lab_order_id_foreign FOREIGN KEY (lab_order_id) REFERENCES lab_orders (id) ON DELETE CASCADE,
    CONSTRAINT lab_order_items_service_tariff_id_foreign FOREIGN KEY (service_tariff_id) REFERENCES service_tariffs (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE pharmacy_sales (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    clinic_id BIGINT UNSIGNED NOT NULL,
    inventory_unit_id BIGINT UNSIGNED NULL,
    visit_id BIGINT UNSIGNED NOT NULL,
    user_id BIGINT UNSIGNED NULL,
    number VARCHAR(30) NOT NULL,
    sale_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL,
    items_total DECIMAL(15,2) NOT NULL DEFAULT 0,
    compounding_fee DECIMAL(15,2) NOT NULL DEFAULT 0,
    total DECIMAL(15,2) NOT NULL DEFAULT 0,
    notes TEXT NULL,
    cancelled_at TIMESTAMP NULL,
    cancelled_by BIGINT UNSIGNED NULL,
    cancellation_reason VARCHAR(255) NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    UNIQUE KEY pharmacy_sales_clinic_id_number_unique (clinic_id, number),
    KEY pharmacy_sales_clinic_id_sale_date_index (clinic_id, sale_date),
    CONSTRAINT pharmacy_sales_clinic_id_foreign FOREIGN KEY (clinic_id) REFERENCES clinics (id) ON DELETE CASCADE,
    CONSTRAINT pharmacy_sales_visit_id_foreign FOREIGN KEY (visit_id) REFERENCES visits (id),
    CONSTRAINT pharmacy_sales_user_id_foreign FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT pharmacy_sales_cancelled_by_foreign FOREIGN KEY (cancelled_by) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE bills (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    clinic_id BIGINT UNSIGNED NOT NULL,
    visit_id BIGINT UNSIGNED NOT NULL,
    guarantor_id BIGINT UNSIGNED NULL,
    user_id BIGINT UNSIGNED NULL,
    number VARCHAR(30) NOT NULL,
    bill_date DATE NOT NULL,
    payer_type VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    services_total DECIMAL(15,2) NOT NULL DEFAULT 0,
    medical_total DECIMAL(15,2) NOT NULL DEFAULT 0,
    nursing_total DECIMAL(15,2) NOT NULL DEFAULT 0,
    laboratory_total DECIMAL(15,2) NOT NULL DEFAULT 0,
    pharmacy_total DECIMAL(15,2) NOT NULL DEFAULT 0,
    discount DECIMAL(15,2) NOT NULL DEFAULT 0,
    total DECIMAL(15,2) NOT NULL DEFAULT 0,
    paid_amount DECIMAL(15,2) NOT NULL DEFAULT 0,
    notes TEXT NULL,
    finalized_at TIMESTAMP NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    UNIQUE KEY bills_visit_id_unique (visit_id),
    UNIQUE KEY bills_clinic_id_number_unique (clinic_id, number),
    KEY bills_clinic_id_status_index (clinic_id, status),
    KEY bills_guarantor_id_status_index (guarantor_id, status),
    CONSTRAINT bills_clinic_id_foreign FOREIGN KEY (clinic_id) REFERENCES clinics (id) ON DELETE CASCADE,
    CONSTRAINT bills_visit_id_foreign FOREIGN KEY (visit_id) REFERENCES visits (id) ON DELETE CASCADE,
    CONSTRAINT bills_guarantor_id_foreign FOREIGN KEY (guarantor_id) REFERENCES guarantors (id) ON DELETE SET NULL,
    CONSTRAINT bills_user_id_foreign FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE bill_items (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    bill_id BIGINT UNSIGNED NOT NULL,
    service_tariff_id BIGINT UNSIGNED NULL,
    pharmacy_sale_id BIGINT UNSIGNED NULL,
    nursing_action_id BIGINT UNSIGNED NULL,
    medical_action_id BIGINT UNSIGNED NULL,
    lab_order_item_id BIGINT UNSIGNED NULL,
    description VARCHAR(255) NOT NULL,
    quantity INT UNSIGNED NOT NULL,
    unit_price DECIMAL(15,2) NOT NULL DEFAULT 0,
    subtotal DECIMAL(15,2) NOT NULL DEFAULT 0,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    CONSTRAINT bill_items_bill_id_foreign FOREIGN KEY (bill_id) REFERENCES bills (id) ON DELETE CASCADE,
    CONSTRAINT bill_items_service_tariff_id_foreign FOREIGN KEY (service_tariff_id) REFERENCES service_tariffs (id) ON DELETE SET NULL,
    CONSTRAINT bill_items_pharmacy_sale_id_foreign FOREIGN KEY (pharmacy_sale_id) REFERENCES pharmacy_sales (id) ON DELETE SET NULL,
    CONSTRAINT bill_items_nursing_action_id_foreign FOREIGN KEY (nursing_action_id) REFERENCES nursing_actions (id) ON DELETE CASCADE,
    CONSTRAINT bill_items_medical_action_id_foreign FOREIGN KEY (medical_action_id) REFERENCES medical_actions (id) ON DELETE CASCADE,
    CONSTRAINT bill_items_lab_order_item_id_foreign FOREIGN KEY (lab_order_item_id) REFERENCES lab_order_items (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE payments (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    clinic_id BIGINT UNSIGNED NOT NULL,
    bill_id BIGINT UNSIGNED NOT NULL,
    cash_session_id BIGINT UNSIGNED NULL,
    user_id BIGINT UNSIGNED NULL,
    number VARCHAR(30) NOT NULL,
    payer_type VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    paid_at TIMESTAMP NOT NULL,
    amount DECIMAL(15,2) NOT NULL DEFAULT 0,
    tendered DECIMAL(15,2) NOT NULL DEFAULT 0,
    change_amount DECIMAL(15,2) NOT NULL DEFAULT 0,
    notes TEXT NULL,
    cancelled_at TIMESTAMP NULL,
    cancelled_by BIGINT UNSIGNED NULL,
    cancellation_reason VARCHAR(255) NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    UNIQUE KEY payments_clinic_id_number_unique (clinic_id, number),
    KEY payments_clinic_id_paid_at_index (clinic_id, paid_at),
    KEY payments_user_id_paid_at_index (user_id, paid_at),
    CONSTRAINT payments_clinic_id_foreign FOREIGN KEY (clinic_id) REFERENCES clinics (id) ON DELETE CASCADE,
    CONSTRAINT payments_bill_id_foreign FOREIGN KEY (bill_id) REFERENCES bills (id) ON DELETE CASCADE,
    CONSTRAINT payments_cash_session_id_foreign FOREIGN KEY (cash_session_id) REFERENCES cash_sessions (id) ON DELETE SET NULL,
    CONSTRAINT payments_user_id_foreign FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT payments_cancelled_by_foreign FOREIGN KEY (cancelled_by) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE payment_details (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    payment_id BIGINT UNSIGNED NOT NULL,
    method VARCHAR(20) NOT NULL,
    amount DECIMAL(15,2) NOT NULL,
    reference VARCHAR(100) NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    CONSTRAINT payment_details_payment_id_foreign FOREIGN KEY (payment_id) REFERENCES payments (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE cash_transactions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    clinic_id BIGINT UNSIGNED NOT NULL,
    cash_session_id BIGINT UNSIGNED NULL,
    user_id BIGINT UNSIGNED NULL,
    number VARCHAR(30) NOT NULL,
    type VARCHAR(10) NOT NULL,
    category VARCHAR(30) NOT NULL,
    method VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    transaction_date DATE NOT NULL,
    amount DECIMAL(15,2) NOT NULL,
    description VARCHAR(255) NOT NULL,
    reference VARCHAR(100) NULL,
    cancelled_at TIMESTAMP NULL,
    cancelled_by BIGINT UNSIGNED NULL,
    cancellation_reason VARCHAR(255) NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    UNIQUE KEY cash_transactions_clinic_id_number_unique (clinic_id, number),
    KEY cash_transactions_clinic_id_type_transaction_date_index (clinic_id, type, transaction_date),
    CONSTRAINT cash_transactions_clinic_id_foreign FOREIGN KEY (clinic_id) REFERENCES clinics (id) ON DELETE CASCADE,
    CONSTRAINT cash_transactions_cash_session_id_foreign FOREIGN KEY (cash_session_id) REFERENCES cash_sessions (id) ON DELETE SET NULL,
    CONSTRAINT cash_transactions_user_id_foreign FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT cash_transactions_cancelled_by_foreign FOREIGN KEY (cancelled_by) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
